--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-22 20:48:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16845)
-- Name: agencies; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.agencies (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    region_id bigint NOT NULL
);


ALTER TABLE public.agencies OWNER TO starboost_user;

--
-- TOC entry 217 (class 1259 OID 16844)
-- Name: agencies_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.agencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17026)
-- Name: challenge_participants; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_participants (
    id bigint NOT NULL,
    agency_id bigint,
    region_id bigint,
    role character varying(255) NOT NULL,
    total_contracts integer,
    total_revenue double precision,
    total_score integer,
    challenge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    CONSTRAINT challenge_participants_role_check CHECK (((role)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'AGENT'::character varying])::text[])))
);


ALTER TABLE public.challenge_participants OWNER TO starboost_user;

--
-- TOC entry 233 (class 1259 OID 17025)
-- Name: challenge_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.challenge_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16852)
-- Name: challenge_products; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_products (
    challenge_id bigint NOT NULL,
    target_products character varying(255),
    CONSTRAINT challenge_products_target_products_check CHECK (((target_products)::text = ANY ((ARRAY['Trik_Esslama'::character varying, 'Dar_Esslama'::character varying, 'STARCARE'::character varying, 'STARCARE_International'::character varying, 'Assistance_Voyage'::character varying, 'Décès_Prévoyance'::character varying, 'Garantie_Accidents_de_la_Vie_Individuel'::character varying, 'Assurance_Emprunteur'::character varying, 'Assurance_Junior'::character varying, 'Hayya'::character varying, 'Avenir_Jeunesse'::character varying, 'Vie_Nouvelle'::character varying, 'Slamet_Errezk'::character varying, 'Multirisque_Agricole'::character varying, 'Santé_Collective'::character varying, 'Retraite_Collective'::character varying, 'Indemnité_de_Départ_à_la_Retraite'::character varying, 'Responsabilité_Civile_Décennale'::character varying, 'Tous_Risques_Chantier'::character varying, 'Transport_Facultés'::character varying, 'Flotte_Automobile'::character varying, 'Homme_Clé'::character varying])::text[])))
);


ALTER TABLE public.challenge_products OWNER TO starboost_user;

--
-- TOC entry 236 (class 1259 OID 17088)
-- Name: challenge_reward_rules; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_reward_rules (
    id bigint NOT NULL,
    base_amount double precision NOT NULL,
    challenge_id bigint NOT NULL,
    payout_type character varying(255) NOT NULL,
    role_category character varying(255) NOT NULL,
    tier_max double precision NOT NULL,
    tier_min double precision NOT NULL,
    CONSTRAINT challenge_reward_rules_payout_type_check CHECK (((payout_type)::text = ANY ((ARRAY['FIXED_TIERS'::character varying, 'PERCENT_TIERS'::character varying, 'RANK_TIERS'::character varying])::text[]))),
    CONSTRAINT challenge_reward_rules_role_category_check CHECK (((role_category)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'AGENT'::character varying])::text[])))
);


ALTER TABLE public.challenge_reward_rules OWNER TO starboost_user;

--
-- TOC entry 235 (class 1259 OID 17087)
-- Name: challenge_reward_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.challenge_reward_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_reward_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16942)
-- Name: challenge_rules; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_rules (
    id bigint NOT NULL,
    contract_type character varying(255),
    pack_type character varying(255),
    transaction_nature character varying(255),
    challenge_id bigint NOT NULL,
    CONSTRAINT challenge_rules_contract_type_check CHECK (((contract_type)::text = ANY ((ARRAY['RENOUVELABLE'::character varying, 'FORFAITAIRE'::character varying])::text[]))),
    CONSTRAINT challenge_rules_pack_type_check CHECK (((pack_type)::text = ANY ((ARRAY['SERENITE'::character varying, 'SUPER_SECURITE'::character varying, 'SECURITE_PLUS'::character varying, 'SECURITE'::character varying, 'ETUDIANT'::character varying, 'PROPRIETAIRE_NON_OCCUPANT'::character varying, 'VISA'::character varying, 'GOLD'::character varying, 'ASSISTANCE_BUSINESS'::character varying, 'ASSISTANCE_ETUDIANT'::character varying, 'ASSISTANCE_PELERINAGE'::character varying])::text[]))),
    CONSTRAINT challenge_rules_transaction_nature_check CHECK (((transaction_nature)::text = ANY ((ARRAY['AFFAIRE_NOUVELLE'::character varying, 'TRANSFERT_EXTERNE'::character varying, 'VERSEMENT_LIBRE'::character varying])::text[])))
);


ALTER TABLE public.challenge_rules OWNER TO starboost_user;

--
-- TOC entry 229 (class 1259 OID 16941)
-- Name: challenge_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.challenge_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16856)
-- Name: challenge_target_roles; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_target_roles (
    challenge_id bigint NOT NULL,
    target_roles character varying(255),
    CONSTRAINT challenge_target_roles_target_roles_check CHECK (((target_roles)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'AGENT'::character varying])::text[])))
);


ALTER TABLE public.challenge_target_roles OWNER TO starboost_user;

--
-- TOC entry 238 (class 1259 OID 17098)
-- Name: challenge_winning_rules; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenge_winning_rules (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    condition_type character varying(255) NOT NULL,
    role_category character varying(255) NOT NULL,
    threshold_min double precision NOT NULL,
    formula_details oid,
    CONSTRAINT challenge_winning_rules_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['MIN_CONTRACTS'::character varying, 'MIN_REVENUE'::character varying, 'MIN_AVG_PER_COMMERCIAL'::character varying, 'MIN_AVG_PER_PV'::character varying, 'WEIGHTED_AVG_AGENCY'::character varying, 'WEIGHTED_AVG_REGION'::character varying])::text[]))),
    CONSTRAINT challenge_winning_rules_role_category_check CHECK (((role_category)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'AGENT'::character varying])::text[])))
);


ALTER TABLE public.challenge_winning_rules OWNER TO starboost_user;

--
-- TOC entry 237 (class 1259 OID 17097)
-- Name: challenge_winning_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.challenge_winning_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_winning_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16861)
-- Name: challenges; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.challenges (
    id bigint NOT NULL,
    agency_manager_condition character varying(255),
    agent_reward_details oid,
    agent_reward_type character varying(255),
    contract_type character varying(255),
    deleted boolean NOT NULL,
    employee_reward_details oid,
    employee_reward_type character varying(255),
    end_date date NOT NULL,
    min_contracts_agent integer,
    min_contracts_commercial integer,
    min_revenue_agent double precision,
    min_revenue_commercial double precision,
    name character varying(255) NOT NULL,
    other_agent_conditions character varying(255),
    other_commercial_conditions character varying(255),
    other_conditions character varying(255),
    region_manager_condition character varying(255),
    star_boost_type character varying(255),
    star_boost_value character varying(255),
    start_date date NOT NULL,
    status character varying(255),
    transaction_nature character varying(255),
    CONSTRAINT challenges_agent_reward_type_check CHECK (((agent_reward_type)::text = ANY ((ARRAY['TIERED'::character varying, 'FIXED'::character varying, 'COMMISSION'::character varying])::text[]))),
    CONSTRAINT challenges_contract_type_check CHECK (((contract_type)::text = ANY ((ARRAY['RENOUVELABLE'::character varying, 'FORFAITAIRE'::character varying])::text[]))),
    CONSTRAINT challenges_employee_reward_type_check CHECK (((employee_reward_type)::text = ANY ((ARRAY['TIERED'::character varying, 'FIXED'::character varying, 'COMMISSION'::character varying])::text[]))),
    CONSTRAINT challenges_star_boost_type_check CHECK (((star_boost_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'COLLECTIVE'::character varying, 'GLOBAL'::character varying])::text[]))),
    CONSTRAINT challenges_status_check CHECK (((status)::text = ANY ((ARRAY['ONGOING'::character varying, 'ENDED'::character varying])::text[]))),
    CONSTRAINT challenges_transaction_nature_check CHECK (((transaction_nature)::text = ANY ((ARRAY['AFFAIRE_NOUVELLE'::character varying, 'TRANSFERT_EXTERNE'::character varying, 'VERSEMENT_LIBRE'::character varying])::text[])))
);


ALTER TABLE public.challenges OWNER TO starboost_user;

--
-- TOC entry 221 (class 1259 OID 16860)
-- Name: challenges_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.challenges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16875)
-- Name: regions; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.regions (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.regions OWNER TO starboost_user;

--
-- TOC entry 223 (class 1259 OID 16874)
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16883)
-- Name: sales_transaction; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.sales_transaction (
    id bigint NOT NULL,
    agency_id bigint,
    contract_type character varying(255),
    premium double precision,
    product character varying(255),
    region_id bigint,
    sale_date timestamp(6) without time zone,
    seller_id bigint,
    seller_name character varying(255),
    seller_role character varying(255),
    transaction_nature character varying(255),
    challenge_id bigint,
    CONSTRAINT sales_transaction_contract_type_check CHECK (((contract_type)::text = ANY ((ARRAY['RENOUVELABLE'::character varying, 'FORFAITAIRE'::character varying])::text[]))),
    CONSTRAINT sales_transaction_product_check CHECK (((product)::text = ANY ((ARRAY['Trik_Esslama'::character varying, 'Dar_Esslama'::character varying, 'STARCARE'::character varying, 'STARCARE_International'::character varying, 'Assistance_Voyage'::character varying, 'Décès_Prévoyance'::character varying, 'Garantie_Accidents_de_la_Vie_Individuel'::character varying, 'Assurance_Emprunteur'::character varying, 'Assurance_Junior'::character varying, 'Hayya'::character varying, 'Avenir_Jeunesse'::character varying, 'Vie_Nouvelle'::character varying, 'Slamet_Errezk'::character varying, 'Multirisque_Agricole'::character varying, 'Santé_Collective'::character varying, 'Retraite_Collective'::character varying, 'Indemnité_de_Départ_à_la_Retraite'::character varying, 'Responsabilité_Civile_Décennale'::character varying, 'Tous_Risques_Chantier'::character varying, 'Transport_Facultés'::character varying, 'Flotte_Automobile'::character varying, 'Homme_Clé'::character varying])::text[]))),
    CONSTRAINT sales_transaction_seller_role_check CHECK (((seller_role)::text = ANY ((ARRAY['COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'AGENT'::character varying])::text[]))),
    CONSTRAINT sales_transaction_transaction_nature_check CHECK (((transaction_nature)::text = ANY ((ARRAY['AFFAIRE_NOUVELLE'::character varying, 'TRANSFERT_EXTERNE'::character varying, 'VERSEMENT_LIBRE'::character varying])::text[])))
);


ALTER TABLE public.sales_transaction OWNER TO starboost_user;

--
-- TOC entry 225 (class 1259 OID 16882)
-- Name: sales_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.sales_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17005)
-- Name: score_rules; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.score_rules (
    id bigint NOT NULL,
    contract_type character varying(255),
    pack_type character varying(255),
    points integer,
    revenue_unit integer,
    score_type character varying(255),
    challenge_id bigint NOT NULL,
    CONSTRAINT score_rules_contract_type_check CHECK (((contract_type)::text = ANY ((ARRAY['RENOUVELABLE'::character varying, 'FORFAITAIRE'::character varying])::text[]))),
    CONSTRAINT score_rules_pack_type_check CHECK (((pack_type)::text = ANY ((ARRAY['SERENITE'::character varying, 'SUPER_SECURITE'::character varying, 'SECURITE_PLUS'::character varying, 'SECURITE'::character varying, 'ETUDIANT'::character varying, 'PROPRIETAIRE_NON_OCCUPANT'::character varying, 'VISA'::character varying, 'GOLD'::character varying, 'ASSISTANCE_BUSINESS'::character varying, 'ASSISTANCE_ETUDIANT'::character varying, 'ASSISTANCE_PELERINAGE'::character varying])::text[]))),
    CONSTRAINT score_rules_score_type_check CHECK (((score_type)::text = ANY ((ARRAY['CONTRACT'::character varying, 'PACK'::character varying, 'REVENUE'::character varying])::text[])))
);


ALTER TABLE public.score_rules OWNER TO starboost_user;

--
-- TOC entry 231 (class 1259 OID 17004)
-- Name: score_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.score_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.score_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16895)
-- Name: users; Type: TABLE; Schema: public; Owner: starboost_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    registration_number character varying(255),
    role character varying(255) NOT NULL,
    agency_id bigint,
    region_id bigint,
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['M'::character varying, 'F'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['AGENT'::character varying, 'COMMERCIAL'::character varying, 'AGENCY_MANAGER'::character varying, 'REGIONAL_MANAGER'::character varying, 'ANIMATOR'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO starboost_user;

--
-- TOC entry 227 (class 1259 OID 16894)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: starboost_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4721 (class 2606 OID 16851)
-- Name: agencies agencies_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.agencies
    ADD CONSTRAINT agencies_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 17031)
-- Name: challenge_participants challenge_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_participants
    ADD CONSTRAINT challenge_participants_pkey PRIMARY KEY (id);


--
-- TOC entry 4745 (class 2606 OID 17096)
-- Name: challenge_reward_rules challenge_reward_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_reward_rules
    ADD CONSTRAINT challenge_reward_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 4739 (class 2606 OID 16951)
-- Name: challenge_rules challenge_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_rules
    ADD CONSTRAINT challenge_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 4747 (class 2606 OID 17106)
-- Name: challenge_winning_rules challenge_winning_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_winning_rules
    ADD CONSTRAINT challenge_winning_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 4725 (class 2606 OID 16873)
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (id);


--
-- TOC entry 4727 (class 2606 OID 16881)
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 16893)
-- Name: sales_transaction sales_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.sales_transaction
    ADD CONSTRAINT sales_transaction_pkey PRIMARY KEY (id);


--
-- TOC entry 4741 (class 2606 OID 17014)
-- Name: score_rules score_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.score_rules
    ADD CONSTRAINT score_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 4729 (class 2606 OID 16907)
-- Name: regions uk375c9j7h9mbq52nyh2m7xyqwp; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT uk375c9j7h9mbq52nyh2m7xyqwp UNIQUE (code);


--
-- TOC entry 4733 (class 2606 OID 16909)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4735 (class 2606 OID 16911)
-- Name: users ukhvimm8nhgcwcxx469t9vo3pgg; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukhvimm8nhgcwcxx469t9vo3pgg UNIQUE (registration_number);


--
-- TOC entry 4723 (class 2606 OID 16905)
-- Name: agencies ukog25hrdt7u2ots7k3c0lva021; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.agencies
    ADD CONSTRAINT ukog25hrdt7u2ots7k3c0lva021 UNIQUE (code);


--
-- TOC entry 4737 (class 2606 OID 16903)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 16912)
-- Name: agencies fk1rjtk7282bvuggsirfijxg8ws; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.agencies
    ADD CONSTRAINT fk1rjtk7282bvuggsirfijxg8ws FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- TOC entry 4758 (class 2606 OID 17107)
-- Name: challenge_reward_rules fk2gfecbut3iojquuyx5lqug1ji; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_reward_rules
    ADD CONSTRAINT fk2gfecbut3iojquuyx5lqug1ji FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4751 (class 2606 OID 17020)
-- Name: sales_transaction fk2pvs324l62llptvhsu9yq2nvg; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.sales_transaction
    ADD CONSTRAINT fk2pvs324l62llptvhsu9yq2nvg FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4749 (class 2606 OID 16917)
-- Name: challenge_products fk3oi2iul5gaai8g1f02kdats8f; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_products
    ADD CONSTRAINT fk3oi2iul5gaai8g1f02kdats8f FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4752 (class 2606 OID 16932)
-- Name: users fk4muym4ujsr1xfh4qc3wsmmrhe; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk4muym4ujsr1xfh4qc3wsmmrhe FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- TOC entry 4750 (class 2606 OID 16922)
-- Name: challenge_target_roles fk638f0jqo8g13aeqaqm16mt7cf; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_target_roles
    ADD CONSTRAINT fk638f0jqo8g13aeqaqm16mt7cf FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4753 (class 2606 OID 16927)
-- Name: users fk7bo7u275rpljcaj3paqbaxbp9; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk7bo7u275rpljcaj3paqbaxbp9 FOREIGN KEY (agency_id) REFERENCES public.agencies(id);


--
-- TOC entry 4756 (class 2606 OID 17032)
-- Name: challenge_participants fk8yestlu1dvje3mnx36fmsbog9; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_participants
    ADD CONSTRAINT fk8yestlu1dvje3mnx36fmsbog9 FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4759 (class 2606 OID 17112)
-- Name: challenge_winning_rules fkd4ntbxeopnifpfoeu45vp45lx; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_winning_rules
    ADD CONSTRAINT fkd4ntbxeopnifpfoeu45vp45lx FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4757 (class 2606 OID 17037)
-- Name: challenge_participants fkmaxbdxkphx8gcxws0wf9mo2ru; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_participants
    ADD CONSTRAINT fkmaxbdxkphx8gcxws0wf9mo2ru FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4755 (class 2606 OID 17015)
-- Name: score_rules fkoi1hx93atfvcwtu9nekv189jc; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.score_rules
    ADD CONSTRAINT fkoi1hx93atfvcwtu9nekv189jc FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


--
-- TOC entry 4754 (class 2606 OID 16963)
-- Name: challenge_rules fktq7lhrtt2563dolyp2rc632lr; Type: FK CONSTRAINT; Schema: public; Owner: starboost_user
--

ALTER TABLE ONLY public.challenge_rules
    ADD CONSTRAINT fktq7lhrtt2563dolyp2rc632lr FOREIGN KEY (challenge_id) REFERENCES public.challenges(id);


-- Completed on 2025-05-22 20:48:47

--
-- PostgreSQL database dump complete
--

